import { useMemo, useState } from "react";
import { ArrowLeft, CheckCircle2, Download, FileUp, RefreshCw } from "lucide-react";
import { Link } from "wouter";
import { products } from "@/data/products";

const workerUrl = String(import.meta.env.VITE_CLOUDFLARE_WORKER_URL || "").replace(/\/$/, "");
const headers = ["id", "sourceProductId", "name", "catalogName", "category", "subCategory", "brand", "price", "referencePrice", "currency", "description", "sizes", "colors", "stock", "shop", "shopUrl", "url", "images", "tags", "collectedAt", "reviewStatus", "reviewNote", "platformLinks"];
type Preview = { total: number; valid: number; invalid: { row: number; error: string }[]; sample: Record<string, unknown>[] };
function parseCsv(text: string) { const rows: string[][] = []; let row: string[] = []; let cell = ""; let quoted = false; for (let i = 0; i < text.length; i += 1) { const char = text[i]; const next = text[i + 1]; if (char === '"' && quoted && next === '"') { cell += '"'; i += 1; } else if (char === '"') quoted = !quoted; else if (char === "," && !quoted) { row.push(cell); cell = ""; } else if ((char === "\n" || char === "\r") && !quoted) { if (char === "\r" && next === "\n") i += 1; row.push(cell); if (row.some((value) => value.trim())) rows.push(row); row = []; cell = ""; } else cell += char; } if (cell || row.length) { row.push(cell); rows.push(row); } const [rawHead, ...data] = rows; const head = rawHead?.map((value) => value.trim()) || []; return data.map((values) => Object.fromEntries(head.map((key, index) => [key, values[index] || ""]))); }
function csvCell(value: unknown) { const text = value == null ? "" : typeof value === "string" ? value : JSON.stringify(value); return /[",\n\r]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; }
function productCsvRow(product: (typeof products)[number]) { const values: Record<string, unknown> = { ...product, sizes: product.sizes.join("|"), colors: product.colors.join("|"), images: product.images.join("|"), tags: product.tags.join("|"), platformLinks: JSON.stringify(product.platformLinks || {}) }; return headers.map((header) => csvCell(values[header])).join(","); }
function downloadTemplate() { const example = products[0]; const blob = new Blob([`\ufeff${headers.join(",")}\n${example ? productCsvRow(example) : ""}\n`], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "productsite-product-template.csv"; anchor.click(); URL.revokeObjectURL(url); }
function downloadCatalog() { const blob = new Blob([`\ufeff${headers.join(",")}\n${products.map(productCsvRow).join("\n")}\n`], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `productsite-products-${new Date().toISOString().slice(0, 10)}.csv`; anchor.click(); URL.revokeObjectURL(url); }
export default function AdminProductImport() { const [key, setKey] = useState(() => window.localStorage.getItem("productsite-admin-key") || ""); const [rows, setRows] = useState<Record<string, unknown>[]>([]); const [preview, setPreview] = useState<Preview | null>(null); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false); const [confirmed, setConfirmed] = useState(false); const [authorized, setAuthorized] = useState(false); const canSubmit = Boolean(workerUrl && key.trim() && rows.length && preview && preview.invalid.length === 0);
  const sample = useMemo(() => preview?.sample || rows.slice(0, 5), [preview, rows]);
  const verifyKey = async () => { if (!workerUrl || !key.trim()) { setMessage("请先输入管理员密钥。"); return; } setLoading(true); setMessage(""); try { const response = await fetch(`${workerUrl}/api/admin/analytics/summary?range=today`, { headers: { "x-admin-api-key": key.trim() } }); if (!response.ok) throw new Error("管理员密钥不正确或 Worker 暂不可用。"); setAuthorized(true); window.localStorage.setItem("productsite-admin-key", key.trim()); setMessage("管理员验证成功，批量产品功能已解锁。"); } catch (error) { setAuthorized(false); setMessage(error instanceof Error ? error.message : "管理员验证失败。"); } finally { setLoading(false); } };
  const onFile = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setMessage(""); setPreview(null); setConfirmed(false); if (!authorized) { setMessage("请先验证管理员密钥。"); return; } try { const parsed = parseCsv(await file.text()); if (!parsed.length) throw new Error("CSV 文件没有可读取的数据行。"); setRows(parsed); setMessage(`已读取 ${parsed.length} 行，点击“校验并预览”。`); } catch (error) { setRows([]); setMessage(error instanceof Error ? error.message : "CSV 文件读取失败。"); } event.target.value = ""; };
  const send = async (commit: boolean) => { if (!workerUrl || !key.trim() || !rows.length) return; setLoading(true); setMessage(""); try { const response = await fetch(`${workerUrl}/api/admin/products/import`, { method: "POST", headers: { "content-type": "application/json", "x-admin-api-key": key.trim() }, body: JSON.stringify({ rows, commit }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error || "商品数据处理失败。"); if (commit) { setConfirmed(true); setMessage(`已确认写入 ${payload.imported || 0} 条商品覆盖数据。`); } else { setPreview(payload); setMessage(payload.invalid?.length ? "发现错误，请修改 CSV 后重新上传。" : "校验通过，请确认后写入网站数据。"); } window.localStorage.setItem("productsite-admin-key", key.trim()); } catch (error) { setMessage(error instanceof Error ? error.message : "商品数据处理失败。"); } finally { setLoading(false); } };
  return <div className="admin-import-page"><header className="admin-import-header"><Link href="/" className="admin-back"><ArrowLeft size={15} /> 返回目录</Link><div><span className="request-eyebrow">CATALOG ADMIN</span><h1>批量上传产品</h1><p>下载模板，填写商品数据，先校验预览，再确认更新。</p></div></header><main className="admin-import-card"><section className="admin-import-tools"><div><h2>1. 下载数据模板</h2><p>请保持第一行字段名不变。数组字段使用竖线分隔，例如：S|M|L。</p></div><div className="admin-import-button-row"><button className="admin-import-button" onClick={downloadTemplate} disabled={!authorized}><Download size={15} /> 下载模板（含真实示例）</button><button className="admin-import-button is-secondary" onClick={downloadCatalog} disabled={!authorized}><Download size={15} /> 导出当前商品数据</button></div></section><section className="admin-import-tools"><div><h2>2. 上传 CSV 文件</h2><p>每次最多 5,000 行；系统只会写入管理员确认后的新增或更新记录。</p></div><label className="admin-import-button"><FileUp size={15} /> 选择 CSV 文件<input type="file" accept=".csv,text/csv" onChange={onFile} disabled={!authorized} hidden /></label></section><section className="admin-import-auth"><label>管理员密钥<input type="password" value={key} onChange={(event) => { setKey(event.target.value); setAuthorized(false); setPreview(null); }} placeholder="ADMIN_API_KEY" /></label><button className="admin-import-button" onClick={() => void verifyKey()} disabled={loading || authorized}>验证管理员密钥</button><button className="admin-import-button" onClick={() => void send(false)} disabled={!authorized || !rows.length || loading}>{loading ? <RefreshCw size={15} className="spin" /> : <CheckCircle2 size={15} />} 校验并预览</button></section>{message && <p className={`admin-import-message ${confirmed ? "is-success" : ""}`}>{message}</p>}{sample.length > 0 && <section className="admin-import-preview"><h2>数据预览 <span>{preview ? `${preview.valid}/${preview.total} 行有效` : `${rows.length} 行待校验`}</span></h2><div className="admin-import-table"><table><thead><tr>{headers.slice(0, 6).map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{sample.map((row, index) => <tr key={index}>{headers.slice(0, 6).map((header) => <td key={header}>{String(row[header] ?? "").slice(0, 80) || "—"}</td>)}</tr>)}</tbody></table></div>{preview?.invalid.length ? <div className="admin-import-errors">{preview.invalid.slice(0, 20).map((item) => <p key={`${item.row}-${item.error}`}>第 {item.row} 行：{item.error}</p>)}</div> : preview && <button className="admin-import-confirm" onClick={() => void send(true)} disabled={!authorized || loading || confirmed}>确认写入网站数据</button>}</section>}<p className="admin-import-note">更新规则：相同 <code>id</code> 会覆盖对应商品覆盖记录；新 <code>id</code> 会新增覆盖记录。不会自动删除未出现在 CSV 中的商品。</p></main></div>;
}
