#!/usr/bin/env python3
"""Build a source-product/style -> image URL map from public Weidian item pages."""
from __future__ import annotations

import html
import json
import re
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[1]
PRODUCTS_TS = ROOT / "client/src/data/products.ts"
OUTPUT_TS = ROOT / "client/src/data/style-images.ts"
MAX_WORKERS = 64
TIMEOUT = 8


def load_products() -> list[dict]:
    text = PRODUCTS_TS.read_text(encoding="utf-8")
    start = text.index("export const products")
    opening = text.index("= [", start) + 2
    ending = text.index("] as Product[]", opening)
    return json.loads(text[opening : ending + 1])


def fetch_style_images(source_id: str, style_keys: list[str]) -> tuple[str, dict[str, str], str | None]:
    url = f"https://weidian.com/item.html?itemID={source_id}"
    try:
        request = Request(url, headers={"User-Agent": "Mozilla/5.0 (compatible; RIVORA style image indexer)"})
        raw = urlopen(request, timeout=TIMEOUT).read().decode("utf-8", "ignore")
        # Weidian SSR embeds JSON as HTML entities: "title":"12;S","img":"...".
        decoded = html.unescape(raw)
        pairs = re.findall(r'"title"\s*:\s*"([^"\\]+)"[^{}]{0,500}?"img"\s*:\s*"(https?://[^"\\]+)"', decoded)
        if not pairs:
            pairs = re.findall(r'"img"\s*:\s*"(https?://[^"\\]+)"[^{}]{0,500}?"title"\s*:\s*"([^"\\]+)"', decoded)
            pairs = [(title, image) for image, title in pairs]
        by_style: dict[str, str] = {}
        wanted = {key.strip().casefold() for key in style_keys if key.strip()}
        for title, image in pairs:
            key = title.split(";", 1)[0].strip().casefold()
            if key in wanted and key not in by_style:
                by_style[key] = image.replace("\\/", "/")
        return source_id, by_style, None
    except Exception as exc:  # Keep partial results; one unavailable source must not stop the build.
        return source_id, {}, f"{type(exc).__name__}: {exc}"


def main() -> int:
    products = load_products()
    groups: dict[str, set[str]] = {}
    for product in products:
        source_id = str(product.get("sourceProductId") or product.get("id") or "").strip()
        sizes = product.get("sizes") or []
        for value in sizes:
            style = str(value).split(";", 1)[0].strip()
            if source_id and style:
                groups.setdefault(source_id, set()).add(style)
    result: dict[str, dict[str, str]] = {}
    failures: list[str] = []
    completed = 0
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as pool:
        futures = [pool.submit(fetch_style_images, source_id, sorted(styles)) for source_id, styles in groups.items()]
        for future in as_completed(futures):
            source_id, mapping, error = future.result()
            completed += 1
            if mapping:
                result[source_id] = mapping
            if error:
                failures.append(f"{source_id}: {error}")
            if completed % 50 == 0 or completed == len(futures):
                print(f"Fetched {completed}/{len(futures)} source pages; matched {sum(len(v) for v in result.values())} styles", flush=True)
    body = "// Generated by scripts/build-style-image-map.py; source images are read from each linked Weidian item page.\n"
    body += "export const styleImages: Record<string, Record<string, string>> = "
    body += json.dumps(result, ensure_ascii=False, indent=2) + " as const;\n"
    OUTPUT_TS.write_text(body, encoding="utf-8")
    if failures:
        print(f"Warnings: {len(failures)} source pages failed", file=sys.stderr)
        for line in failures[:20]:
            print(line, file=sys.stderr)
    print(f"Wrote {OUTPUT_TS} with {len(result)} source products and {sum(len(v) for v in result.values())} style images")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
